### ISSUE TITLE
What color format are you using?

### ISSUE THREAD

**Issue by v1993** [gamer-cndg/omega2-ili9225#1]
I'm trying to use you library as a reference for my own project that will use HW SPI and not include anything except window/framebuffer control.

I'm really confused about what color format are you using, because it seems to differ depending on where I look.

https://github.com/gamer-cndg/omega2-ili9225/blob/eda437aac399e3021162dc1fc0a1e4a231995ebd/src/ILI9225.c#L21

Framebuffer is composed of 16-bit values, makes sense.

https://github.com/gamer-cndg/omega2-ili9225/blob/eda437aac399e3021162dc1fc0a1e4a231995ebd/src/ILI9225.c#L365

Here you still assume 16-bit color, but comment is confusing. RGB666 is 6 bits per color and 18 bits (3 bytes!) in total.

So what color format are you using? Is it possibly RGB565 (2 bytes, 16 bits)?

**Comment by v1993** [comment]
It appears that my guess was correct

https://github.com/Nkawu/TFT_22_ILI9225/blob/a081bfebff552479564511a034f6a1916d74a5f2/src/TFT_22_ILI9225.cpp#L773-L776

It clearly converts color to RGB565 format there.

You might want to change that comment to not confuse future readers. That would be really kind of you!

**Comment by maxgerhardt** [comment]
Indeed the comment is wrong - there is no RGB666 format, what's meant here is RGB-16 bit in RBG565 order.

**Comment by maxgerhardt** [comment]
Fixed per 31b3b607151ca8e6f58f5bc1ecd12d32cb755478
